# Generated by Django 2.0.6 on 2018-07-25 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='purbeurre.Products')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement', to='purbeurre.Products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
